ummapp/lib/django/conf/project_template/project_name/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

ummapp/lib/django/contrib/auth/urls.py
# The views used below are normally mapped in django.contrib.admin.urls.py
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
]

ummapp/lib/social/apps/django_app/urls.py
"""URLs module"""
from django.conf import settings
try:
    from django.conf.urls import patterns, url
except ImportError:
    # Django < 1.4
    from django.conf.urls.defaults import patterns, url


from social.utils import setting_name


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''


urlpatterns = patterns('social.apps.django_app.views',
    # authentication / association
    url(r'^login/(?P<backend>[^/]+){0}$'.format(extra), 'auth',
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), 'complete',
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), 'disconnect',
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+){0}$'
            .format(extra), 'disconnect', name='disconnect_individual'),
)

ummapp/umm_tool/djangae/contrib/gauth/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'djangae.contrib.gauth.views',
    url(r'^login_redirect$', 'login_redirect', name='djangae_login_redirect'),
    url(r'^switch_accounts/$', 'switch_accounts', name='djangae_switch_accounts'),
)

ummapp/umm_tool/djangae/urls.py
from django.conf.urls import patterns, url, include
import djangae.contrib.mappers.urls

urlpatterns = patterns('djangae.views',
    url(r'^start$', 'start'),
    url(r'^start$', 'stop'),
    url(r'^warmup$', 'warmup'),
    url(r'^queue/deferred/?$', 'deferred'),
    url(r'^internalupload/$', 'internalupload', name='djangae_internal_upload_handler'),
    url(r'^mapreduce/', include(djangae.contrib.mappers.urls))
)

ummapp/umm_tool/umm_tool/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^umm/admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('^auth/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'umm_app.views.home'),
    url(r'^task/', "umm_app.views.tasks", name="tasks"),
    url(r'^auth/error/', "umm_app.views.auth_error", name="error"),
    url(r'^login/', "umm_app.views.home", name=""),
    url(r'^umm/$', "umm_app.views.home1", name="home1"),
    url(r'^task_list/(?P<cat_id>\d+)/', 'umm_app.views.task_list', name='task_list'),
    url(r'^left_column_list/(?P<task_id>\d+)/', 'umm_app.views.left_column_list', name='left_column_list'),
    url(r'^elevator_pitch_data/(?P<task_id>\d+)/', 'umm_app.views.elevator_pitch_data', name='elevator_pitch_data'),
    url(r'^right_column_list/(?P<task_id>\d+)/', 'umm_app.views.right_column_list', name='right_column_list'),
    url(r'^combodata/$', 'umm_app.views.combo_data', name='combo_data'),
    url(r'^budget_band/$', 'umm_app.views.budget_band', name='budget_band'),
    url(r'^_ah/', include('djangae.urls')),
    url(r'^knowledgebase/admin/','umm_app.views.manage_admin', name='manage_admin'),
    
    url(r'^get-program-tasks/(?P<program_type_id>[0-9]+)/','umm_app.views.get_program_tasks',name='get_program_tasks'),
    url(r'^get-column-name/','umm_app.views.get_column_name',name='get_column_name'),
    url(r'^add-task-data/','umm_app.views.add_task_data',name='add_task_data'),
    url(r'^get-task-data/(?P<task_id>[0-9]+)','umm_app.views.get_task_data',name='get_task_data'),
    url(r'^get-carousel-column-name/','umm_app.views.get_carousel_column_name',name='get_carousel_column_name'),
    url(r'^add-carousel-data/','umm_app.views.add_carousel_data',name='add_carousel_data'),
    url(r'^get-carousel-data/(?P<sub_process_id>[0-9]+)','umm_app.views.get_carousel_data',name='get_carousel_data'),
    url(r'^get-addldata-column-name/','umm_app.views.get_addldata_column_name',name='get_addldata_column_name'),
    url(r'^add-addldata/','umm_app.views.add_addldata',name='add_addldata'),
    url(r'^get-addldata/(?P<task_id>[0-9]+)','umm_app.views.get_addldata',name='get_addldata'),
    url(r'^get-subprocess-programdata/(?P<sub_process_id>[0-9]+)','umm_app.views.get_subprocess_programdata',name='get_subprocess_programdata'),
    url(r'^add-subprocess-programdata/(?P<sub_process_id>[0-9]+)','umm_app.views.add_subprocess_programdata',name='add_subprocess_programdata'),
    url(r'^edit-subprocess/(?P<sub_process_id>[0-9]+)','umm_app.views.edit_subprocess',name='edit_subprocess'),
    url(r'^delete-carouseldata/(?P<carousel_data_id>[0-9]+)','umm_app.views.delete_carouseldata',name='delete_carouseldata'),
    url(r'^delete-addldata/(?P<additional_data_id>[0-9]+)','umm_app.views.delete_addldata',name='delete_addldata'),
    url(r'^delete-taskdata/(?P<task_data_id>[0-9]+)','umm_app.views.delete_taskdata',name='delete_taskdata'),
    # API

    # Get all processes
    url(r'^get-process/$','umm_app.views.get_process', name='get_process'),
    # Get All Subprocesses
    url(r'^process/(?P<reference_id>[0-9]+)/subprocesses$', 'umm_app.views.subprocess_handler'),
    # Clone Sub Process
    url(r'^process/(?P<process_id>[0-9]+)/sp/(?P<sprocess_name>[A-Za-z0-9-]+)/clone', 'umm_app.views.clone_subprocess'),

    # Delete Process/Subproccess/Program types/ tasks/ task data/ additional data
    url(r'^process/(?P<process_id>[0-9]+)/delete$', 'umm_app.views.delete_process_handler'),
    url(r'^process/(?P<process_id>[0-9]+)/sp/(?P<sub_process_id>[0-9]+)/delete', 'umm_app.views.delete_subprocess_handler'),
    url(r'^programtype/delete', 'umm_app.views.delete_programs_handler'),
    url(r'^programtask/delete', 'umm_app.views.delete_tasks_handler'),
    url(r'^taskdata/(?P<task_data_id>[0-9]+)/delete', 'umm_app.views.delete_taskdata_handler'),
    url(r'^taskadditionaldata/(?P<additional_data_id>[0-9]+)/delete', 'umm_app.views.delete_additionaldata_handler'),
    url(r'^quaterupdate/(?P<data_id>[0-9]+)/delete', 'umm_app.views.delete_subprocess_level_data'),

    # Views
    url(r'^process/(?P<reference_id>[0-9]+)/show$', 'umm_app.views.subprocess_handler', name='subprocess_handler'),
    url(r'^process/(?P<process_id>[0-9]+)/sp/(?P<sprocess_name>[A-Za-z0-9-]+)/edit','umm_app.views.create_task_data',name=''),
    url(r'^process/create/$','umm_app.views.process_handler', name='process_handler'),
    url(r'^process/(?P<process_id>[0-9]+)/sp/(?P<sprocess_name>[A-Za-z0-9-]+)/view$','umm_app.views.show_process_data', name='show_process_data'),

    url(r'^faq/create/$','umm_app.views.faq_handler', name='faq_handler'),
    url(r'^faq/faq_creater/$','umm_app.views.faq_creater', name='faq_creater'),
    url(r'^faq/all/','umm_app.views.faq_all', name='faq_all'),
    url(r'^faq/no-answers/all','umm_app.views.get_faq_unanswered', name='get_faq_unanswered'),
    url(r'^faq/edit/', 'umm_app.views.faq_edit', name='faq_edit'), 
    url(r'^faq/faq_update/', 'umm_app.views.faq_update', name='faq_update'),
    url(r'^faq/faq_delete/', 'umm_app.views.faq_delete', name='faq_delete'),
    url(r'^faq/home_view/', 'umm_app.views.faq_home_view', name='faq_home_view'),
    url(r'^faq/get_faq/', 'umm_app.views.get_faq', name='get_faq'),
    url(r'^faq/faq_creater/user_question/', 'umm_app.views.user_question', name='user_question'),
    
    #Quality Framework
    url(r'^qf/home/', 'umm_app.views.qf_home', name='qf_home'),
    url(r'^qualityframework/create/$','umm_app.views.qualityframework_handler', name='qualityframework_handler'),
    url(r'^get-qualityframework-name/$','umm_app.views.get_qualityframework_name', name='get_qualityframework_name'),
    url(r'^qualityframework/all/$','umm_app.views.get_qualityframework', name='get_qualityframework'),
    url(r'^qf/qf_delete/(?P<qf_id>[0-9]+)$', 'umm_app.views.delete_qualityframework'),
    url(r'^get-qf-data/(?P<qf_id>[0-9]+)','umm_app.views.get_qf_data',name='get_qf_data'),
    url(r'^qualityframework/update/','umm_app.views.qf_update',name='qf_update'),
    
]

ummapp/templates/apollo-index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Advertiser Goals</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap-theme.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css'%}">
		<script src="{% static 'js/jquery-2.2.1.min.js'%}"></script>
	</head>
	<body>
        {% if user and not user.is_anonymous %}
        <div class="container-fluid topbar noborder">
			<div class="col-md-12 logo-img">
  				<div class="col-md-6" >
					<div  class="img-responsive logo" ></div>
				</div>
				<div class="col-md-6" >
					<div class="user" id="username_login">	
						{{ user.get_full_name|default:user.username }} |
						<a href="{% url 'auth:logout' %}?next=/">Logout</a><br>
					{% if is_manager %}
						<a href="/umm/manage-admin/"> Manage Admin</a>
					{% endif %}
					</div>
				</div>
			</div>
		</div>

		<div class="container-fluid main-link">
			<a href="/" class="active"> <h3 clas="adv "> Advertiser Goals </h3> </a>
			<a href="/umm/"> <h3 clas="adv"> UMM apollo Q{{quarter.1}}'{{quarter.2}} </h3> </a>
			<hr class="line2">
		</div>

		<div class="container-fluid">
		    <div class="col-md-12 option">
		      <div class="col-xs-12 col-sm-12 col-md-12 option">

		      <h4> <em class="text-danger">Select your advertiser goals &amp; hit 'Submit' button</em> </h4>

			      <form action="" id="goalform">
		            {% for g_map in goal_map %}
				      <div class="col-md-4">
				      <input type="checkbox" class="task" ><span class="task_name" id={{ g_map.id }}>{{ g_map.goal_name }}</span></input>
				      </div>       
				     {% endfor %}  
				      <div class="clearfix">&nbsp;</div>
				      <div class="pull-right"><button type="submit" class="btn btn-primary sbtn">SUBMIT</button>&nbsp; <button type="button" class="btn btn-default refresh">Refresh</button></div>
			      </form>
		      </div>

		       <div class="clearfix">&nbsp;</div> 

		      	<div class="col-xs-12 col-sm-12 col-md-12 taskwrap">
		       		<h1 class="bottom-row task-list">Task Recommendations</h1>
		     		<div class="clearfix"></div>

				    <div class=" col-xs-12 col-sm-12 col-md-12 taskrecommend">
				      		<h4 class="text-center"> <em class="text-danger"><br>Watch out this space for your task recommendations<br><br></em> </h4>
				    </div>
				    <div class=" col-xs-12 col-sm-12 col-md-12 taskrecommend2">
				      	
				    </div>
	     		</div>
	     		<div class="col-xs-12 col-sm-12 col-md-12 line3"></div>			
			    <div class="col-xs-12 col-sm-12 col-md-12 taskwrap">
		       		<h1 class="bottom-row">Additional Questions</h1>
		     		<div class="clearfix">  </div>
				    <div class="advertiser-goal">
				      		<h4 class="text-center"> <em class="text-danger"><br>Watch out this space for your advertiser goal better<br><br></em> </h4>
				    </div>
			    </div>

			    </div>
			  </div>
			  <script type="text/javascript" src="{% static 'js/custom.js'%}"></script>

          {% else %}
	         <div id="header">
			    <div id="header-content">
			      <a href="/"><div id="logo"></div></a>
			    </div>
			  </div>

			  <div id="extra"></div>

			  <div class="container">
			    <div class="login-container">
			      <div class="login">
		               <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'images/login.png'%}"></div></a>
		                </div>
			    </div>
			  </div>
			  {% if error %}
				  <div id="error">
				  		<p>{{error}}</p>
				  </div>
			  {% endif %}
			  
			  <div class="footer"></div>
         {% endif %} 
  
</body>
</html>

ummapp/templates/apollo_index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Advertiser Goals</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css'%}">
		<!--<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap-theme.min.css'%}">-->
		<link href="{% static 'manage_admin/css/font-awesome.min.css' %}" rel="stylesheet">
		{% if user and not user.is_anonymous %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/new_custom.css'%}">
		{% else %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css'%}">
		<link href="{% static 'manage_admin/css/style.css' %}" rel="stylesheet">
		{% endif %}
		<script src="{% static 'js/jquery-2.2.1.min.js'%}"></script>
		<link rel="shortcut icon" type="image/png" href="{% static 'manage_admin/images/new_favicon.ico'%}"/>
	</head>

	{% if user and not user.is_anonymous %}
	<body>
	{% else %}
	<body  style="background: url({% static 'manage_admin/images/bg.jpg' %}); background-size:cover">
	{% endif %}

	
        {% if user and not user.is_anonymous %}
        <header class="top-section">
		  <div class="container-fluid">
			  <div class="row">
			  	  <div class="col-md-4">
					<a href="/"><img src="{% static 'manage_admin/images/regalix_logo.jpg' %}" alt=""></a>
				  </div>
				  <div class="col-md-8">
					  <ul>
						  <li>{{ user.get_full_name|default:user.username }} </li>		  
						  <li><a href="{% url 'auth:logout' %}?next=/"><i class="fa fa-power-off" aria-hidden="true"></i></a></li>
						  {% if is_manager %}
						  	<li><a href="/knowledgebase/admin/"><i class="fa fa-users" aria-hidden="true"></i></a></li>
						  {% endif %}	
					  </ul>
				  </div>
			  </div>
		</header>

		<section class="top-nav">
		  <div class="container-fluid">
			  <ul>
				  <!--<li><a href="/" class="active">Advertiser Goals</a></li>-->
				  {% for sub_process in sub_processs %}
				  	<li><a href="process/{{sub_process.process.id}}/sp/{{sub_process.url_name}}/view" data-processid="{{sub_process.id}}" class="process">{{sub_process.name}} Q'{{sub_process.quarter.quarter}} {{sub_process.quarter.quarter_year}}</a></li>
				  {%endfor %}
			  </ul>
		  </div>
		</section>

		<!--<section class="sub-category-section">
		  <div class="container-fluid">
			  <h2>Select your advertiser goals & hit 'Submit' button</h2>
			  
			      <form action="" id="goalform">
			      <div class="row">
		            {% for g_map in goal_map %}
				      <div class="col-md-4">
				      <label class="control control--checkbox task_name"  id="{{ g_map.id }}">{{ g_map.goal_name }}
				      <input type="checkbox" class="task" >
				      <div class="control__indicator"></div>
					  </label>
					  </div>
				     {% endfor %} 
				  </div> 
					<button type="button" class="btn btn-default pull-right refresh">Refresh</button>
				      <button type="submit" class="btn btn-primary pull-right sbtn">SUBMIT</button>
			      </form>
		  </div>
		</section>
		<section class="recommendations-section">
		  <div class="container-fluid">
		  	  <div class="white-bg">
				  <h2 class="task-list">Task Recommendations</h2>
				  <div class="clearfix"></div>
				  <div class="taskrecommend">
				  	<p>Watch out this space for your task recommendations</p>
				  </div>
				  <div class="clearfix"></div>
				  <div class="taskrecommend2">
				      	
				    </div>
				  <h2>Additional Questions</h2>
				  <div class="clearfix">  </div>
				  <div class="advertiser-goal">
				  <p>Watch out this space for your advertiser goal better</p>
				  </div>
			  </div>
		  </div>
		</section>-->
			  <script type="text/javascript" src="{% static 'js/custom.js'%}"></script>

          {% else %}
	         <!-- <div id="header">
			    <div id="header-content">
			      <a href="/"><div id="logo"></div></a>
			    </div>
			  </div>

			  <div id="extra"></div>

			  <div class="container">
			    <div class="login-container">
			      <div class="login">
		               <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'images/login.png'%}"></div></a>
		                </div>
			    </div>
			  </div> -->

			  
    
	
			  <div class="container">
			  
				  <div class="login-box ">
					  <div class="box"></div>
				  		<img src="{% static 'manage_admin/images/logo_new.png' %}" alt="">
					  <div class="clearfix"></div>
				  		<a class="btn  btn-social btn-google" href="{% url 'social:begin' 'google-oauth2' %}" >
		            <span class="fa fa-google"></span> Sign in with Google
		          </a>
		          <div class="box2"></div>
				  </div>


			  </div>
				  {% if error %}
					  <div id="error-login-box" class="login-box">
					  		<p>{{error}}</p>
					  </div>
				  {% endif %}
			  
			  
			  
			   
			  
			  

			  
			  <!-- <div class="footer"></div> -->
         {% endif %} 

        </body>
<script src="{% static 'manage_admin/js/jquery.min.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		if ($('.process').length){
			that = $('.process:first')
	    	selected_sub_process = that.attr('data-processid');
	    	url = that.attr('href');
    		$.ajax({
	            url: that.attr('href'),
	            type: 'GET',
	            success: function(data) {
	            	window.location.href = url;
	            	$('.process').removeClass('active');
	            	$('.process[data-processid='+ selected_sub_process + "]").addClass('active');

	            },
	            error: function(xhr, status, error) {
	                var err = eval("(" + xhr.responseText + ")");
	                alert(err.Message);
	                //alert("Something went wrong, please try after some time");
	            }	

	        });
		}
	    /*$("body").on("click", ".process", function(e){
	    	e.preventDefault()
	    	selected_sub_process = $(this).attr('data-processid');
    		$.ajax({
	            url: $(this).attr('href'),
	            type: 'GET',
	            success: function(data) {

	            	$('.process').removeClass('active');
	            	$('.process[data-processid='+ selected_sub_process + "]").addClass('active');

	            },
	            error: function(xhr, status, error) {
	                var err = eval("(" + xhr.responseText + ")");
	                alert(err.Message);
	                //alert("Something went wrong, please try after some time");
	            }	

	        });	    	
	    	

	    });*/
	});
</script>  
</body>
</html>
	

ummapp/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Advertiser Goals</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap-theme.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css'%}">
		<script src="{% static 'js/jquery-2.2.1.min.js'%}"></script>
	</head>
	<body>
        {% if user and not user.is_anonymous %}
        <div class="container-fluid topbar noborder">
			<div class="col-md-12 logo-img">
  				<div class="col-md-6" >
					<div  class="img-responsive logo" ></div>
				</div>
				<div class="col-md-6" >
					<div class="user" id="username_login">	
						{{ user.get_full_name|default:user.username }} |
						<a href="{% url 'auth:logout' %}?next=/">Logout</a>
					</div>
				</div>
			</div>
		</div>

		<div class="container-fluid main-link">
			<a href="/" class="active"> <h3 clas="adv "> Advertiser Goals </h3> </a>
			<a href="/umm/"> <h3 clas="adv"> UMM offerings Q{{quarter.1}}'{{quarter.2}} </h3> </a>
			<hr class="line2">
		</div>

		<div class="container-fluid">
		    <div class="col-md-12 option">
		      <div class="col-xs-12 col-sm-12 col-md-12 option">

		      <h4> <em class="text-danger">Select your advertiser goals &amp; hit 'Submit' button</em> </h4>

			      <form action="" id="goalform">
		            {% for g_map in goal_map %}
				      <div class="col-md-4">
				      <input type="checkbox" class="task" ><span class="task_name" id={{ g_map.id }}>{{ g_map.goal_name }}</span></input>
				      </div>       
				     {% endfor %}  
				      <div class="clearfix">&nbsp;</div>
				      <div class="pull-right"><button type="submit" class="btn btn-primary sbtn">SUBMIT</button>&nbsp; <button type="button" class="btn btn-default refresh">Refresh</button></div>
			      </form>
		      </div>

		       <div class="clearfix">&nbsp;</div> 

		      	<div class="col-xs-12 col-sm-12 col-md-12 taskwrap">
		       		<h1 class="bottom-row task-list">Task Recommendations</h1>
		     		<div class="clearfix"></div>

				    <div class=" col-xs-12 col-sm-12 col-md-12 taskrecommend">
				      		<h4 class="text-center"> <em class="text-danger"><br>Watch out this space for your task recommendations<br><br></em> </h4>
				    </div>
				    <div class=" col-xs-12 col-sm-12 col-md-12 taskrecommend2">
				      	
				    </div>
	     		</div>
	     		<div class="col-xs-12 col-sm-12 col-md-12 line3"></div>			
			    <div class="col-xs-12 col-sm-12 col-md-12 taskwrap">
		       		<h1 class="bottom-row">Additional Questions</h1>
		     		<div class="clearfix">  </div>
				    <div class="advertiser-goal">
				      		<h4 class="text-center"> <em class="text-danger"><br>Watch out this space for your advertiser goal better<br><br></em> </h4>
				    </div>
			    </div>

			    </div>
			  </div>
			  <script type="text/javascript" src="{% static 'js/custom.js'%}"></script>

          {% else %}
	         <div id="header">
			    <div id="header-content">
			      <a href="/"><div id="logo"></div></a>
			    </div>
			  </div>

			  <div id="extra"></div>

			  <div class="container">
			    <div class="login-container">
			      <div class="login">
		               <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'images/login.png'%}"></div></a>
		                </div>
			    </div>
			  </div>

<!-- 
					new log-in page url
			    <body style="background: url(images/bg.jpg); background-size:cover">
    
	
				  <div class="container">
				  
					  <div class="login-box ">
						  <div class="box"></div>
					  		<img src="images/logo.png" alt="">
						  <div class="clearfix"></div>
					  		<a class="btn  btn-social btn-google" s>
			            <span class="fa fa-google"></span> Sign in with Google
			          </a>
			          <div class="box2"></div>
					  </div>
				  </div>
			  
			  
			  
			   
			    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
			    <script src="js/jquery.min.js"></script>
			    <!-- Include all compiled plugins (below), or include individual files as needed -->
			    <script src="js/bootstrap.min.js"></script>
			  </body> -->


			  {% if error %}
				  <div id="error">
				  		<p>{{error}}</p>
				  </div>
			  {% endif %}
			  
			  <div class="footer"></div>
         {% endif %} 
  
</body>
</html>